Checking if build is true before prompting or initializing
knative-sandbox/kn-plugin-func pull request #694
Opened 2021-12-01 08:47 UTC by salaboy

# Changes
- :bug: Checks the build configuration argument before prompting build questions or trying to check if the func project has been initialized. 

/kind bug

Fixes #693

2021-12-01 09:09 UTC, salaboy commented
/assign @shinigambit

2021-12-01 09:16 UTC, salaboy commented
@shinigambit This is just a way of doing this.. we need unit tests for this one .. and see what other people thinks about this change.

2022-01-24 13:14 UTC, lkingland requested changes
Perhaps consider placing the logic in `.Prompt()` to avoid skipping prompts for other attributes.

2022-01-24 13:14 UTC, lkingland commented on cmd/deploy.go
> +	if config.Build {
This is a good idea, but I think it should actually be part of the `Prompt` method.  For two reasons, first, this causes the user to never be prompted for other attributes, such as Namespace, which are pertinent whether or not build is enabled.  Second, the purpose of this `if` statement is to adjust how `Prompt` is implemented, so it should be part of Prompt's implementation.

The way this is can be handled is by splitting Prompt into multiple sets of queries (you can see this in action in `invoke.go` which only asks for `Data` if `File` was not specified.

2022-10-03 12:33 UTC, lkingland commented
The referenced issue was fixed in #1071

2022-10-03 12:33 UTC, closed without merging